name: Laravel Deploy Productions

on:
  push:
    branches:
      - main

jobs:
  deploy-laravel:
    name: Laravel Deploy Action
    runs-on: ubuntu-latest

    steps:
      - name: Set up EC2 SSH access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LARAVEL_ACTION_PRIVATE }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.LARAVEL_ACTION_IP }} >> ~/.ssh/known_hosts

      - name: Deploy Laravel on EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.LARAVEL_ACTION_USER }}@${{ secrets.LARAVEL_ACTION_IP }} << 'EOF'
            set -e

            echo 'Navigate to laravel folder'
            cd /var/www/html

            echo 'Pulling data from server'
            git pull origin ${{ github.ref_name }}

            echo 'Installing dependencies'
            composer install --no-dev --optimize-autoloader
          EOF
